### ISSUE TITLE
Settings for MaterialPageRoute

### ISSUE THREAD

**Issue by i5o** [vishna/voyager#45]
Hello!
I want to start saying that I found voyager by accident, and it's been wonderful so far.

The only thing I'm wondering (just asking), is why isn't "settings" passed to `return MaterialPageRoute<dynamic>(builder: builder)` in router.dart.
My URL in my app wasn't changing when I did `.pushNamed(url)` so I had to add `settings: settings` to the MaterialPageRoute (in router.dart) for it to work.

Is this intended?

**Comment by vishna** [comment]
hmm... might be I overlooked it, saw your [PR](https://github.com/vishna/voyager/pull/46) & commented, happy to include otherwise
