### ISSUE TITLE
Page constructors get called when they shouldn't?

### ISSUE THREAD

**Issue by i5o** [vishna/voyager#47]
I'm trying to explain this issue the best I can..
So I'm going to url:
`"#/a/b/c"`

Is there any reason on why the constructor of `a` then `b` then `c` gets called?
I also get an error if I don't declare `a`, `a/b/` in routes.yaml

This is how I've setup routes.yaml to avoid errors of RouteNotFound

```
'/store/':
  widget: LoadingCentered
'/store/select':
  widget: StoreSelectPage
'/store/:idr/':
  widget: LoadingCentered
'/store/:idr/:ids':
  widget: LoadingCentered
'/store/:idr/:ids/home':
  widget: StoreHomePage
  url: '/store/%{idr}/%{ids}/home'
  idr: '%{idr}'
  ids: '%{ids}'
```

FYI: I redirect to `/store/:idr/:ids/home` after the user selects one store in `/store/select`
`global.navigatorKey.currentState.pushReplacementNamed("/store/${store.retailer.retailerNumber}/${store.storeNumber}/home");`

**Comment by vishna** [comment]
@i5o this is probably framework doing its assumptions:

https://github.com/vishna/voyager#integrating-with-materialapp (mentioned here)

https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html (more here)

> If the route name starts with a slash, then it is treated as a "deep link", and before this route is pushed, the routes leading to this one are pushed also. For example, if the route was /a/b/c, then the app would start with the four routes /, /a, /a/b, and /a/b/c loaded, in that order. Even if the route was just /a, the app would start with / and /a loaded. You can use the onGenerateInitialRoutes property to override this behavior.

I was facing this once when using Nested Navigator and what I did was replacing path `/` with a `\` then wrapped onGenerateMethod with a method that would replace slashes back and pass them to voyager - ugly af but worked 🤷 

Not sure what you can do about it if you're using web tho, maybe there's option somewhere in Flutter to disable this behaviour

**Comment by i5o** [comment]
Yes, it surely is annoying ugh.

**Comment by i5o** [comment]
I "fiixed"? It by removing the start "/" on each url, now it works good :]
Thx for your awesome work
